# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, null=True)),
                ('gender', models.CharField(max_length=16, null=True)),
                ('location', models.CharField(max_length=256, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 3, 27, 10, 12, 52, 716917))),
                ('imagepath', models.CharField(max_length=256, null=True)),
                ('label', models.TextField()),
            ],
        ),
    ]
